name: Release

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  artifact:
    uses: yonatankarp/github-actions/.github/workflows/build-jar-artifact.yml@v1
    with:
      tag: ${{ github.event.release.tag_name }}
      github-token: ${{ secrets.REVIEWER_GITHUB_TOKEN }}
